# Generated by Django 5.2 on 2025-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('room_type', models.CharField(choices=[('Standard room', 'standard'), ('Deluxe room', 'deluxe'), ('Apartment', 'suite'), ('penthouse', 'Penthouse')], max_length=20)),
                ('additional_wishes', models.TextField(blank=True)),
            ],
        ),
    ]
