# Generated by Django 5.2 on 2025-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard room'), ('deluxe', 'Deluxe room'), ('suite', 'Apartment'), ('penthouse', 'Penthouse')], max_length=20),
        ),
    ]
