# Generated by Django 5.2 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard room'), ('deluxe', 'Deluxe room'), ('suite', 'Apartment'), ('penthouse', 'Penthouse')], max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
